#!/usr/bin/env python3
import os
import random
from twilio.rest import Client
from flask import Flask
app = Flask(__name__)


# Create client
account_sid = 'AC941ec26e5dd644cc25ec4d8d1562b5d3'
auth_token = os.environ.get('TWILIO_TOKEN')
phone_number_1 = os.environ.get('PHONE_NUMBER_1')
phone_number_2 = os.environ.get('PHONE_NUMBER_2')
print(f'{auth_token}')
client = Client(account_sid, auth_token)

questions = ["Wat zijn jouw topmomenten?",
"Wat is je grootste dilemma?",
"Wat was een conflictmoment de afgelopen tijd?",
"Wat was een keerpunt of ommekeer?",
"Wat was voor jou een moment of truth?",
"Wie zijn jouw helden?",
"Wat is je streven?",
"Wat wil je achterlaten?",
"Wie zijn je gangmakers, je mentoren?",
"Voor wie doe je het?",
"Wat drijft je?",
"Waar geloof je in?",
"Wat was de naam van de eerste jongen waar je een crush op had en waarom vond je hem/haar leuk?",
"Is er iets waar je spijt van hebt dat je wél of juist niet gedaan hebt?",
"Kun je beter met je vader of met je moeder opschieten?",
"Welk gerecht kun jij het beste klaarmaken?",
"Als je jouw voornaam zou kunnen veranderen, welke naam zou je dan kiezen?",
"Kan je hoelahoepen?",
"Waarvoor zou jij je schamen/wat zou jij gênant vinden als andere mensen het zien?",
"Zou jij koningin/koning kunnen zijn?",
"Als je maar één hobby zou mogen uitvoeren... Welke zou het dan zijn?",
"Op wie ben je jaloers en waarom? Dit mag zowel een fictief persoon zijn als een echt persoon...",
"Wat is de mooiste plek op aarde en waarom?",
"Geloof je in geesten of aliens?",
"Zijn je voeten even groot?",
"Van welk liedje word je emotioneel?",
"Van welk liedje word je happy?",
"Weet je hoe je het spel Domino's speelt?",
"Wat ligt er onder je bed?",
"Heb je ooit een prank call gepleegd?",
"Ben je trots op jezelf en hoe je nu in het leven staat en wat je doet?",
"Heb je ooit iets gebroken?",
"Heb je ooit iets gewonnen?",
"Welk eten zou je absoluut nooit onder welke omstandigheden dan ook eten? ",
"Waarmee kun je jou opvrolijken als je een vreselijke slechte dag achter de rug hebt?",
"Heeft iets of iemand ooit je leven gered?",
"Zou je een kind kunnen adopteren?",
"Is er iets wat misschien beschamend is, maar wat je toch zou willen proberen? (Denk aan bijvoorbeeld paaldansen)",
"Als je een taart zou zijn... Welke taart ben je dan?",
"Wat is het meest belangrijke materiële ding dat je hebt?",
"Wat is tot nu toe de mooiste herinnering die je hebt?",
"Wanneer heb je voor het laatst gehuild?",
"Hoe oud was je moeder toen jij geboren werd?",
"Met welke celeb zou jij beste vriendinnen willen zijn?",
"Is er iets waar je spijt van hebt? ",
"Is er iets wat ik kan doen, waardoor je leven leuker en makkelijker verloopt?",
"Noem één ding dat mensen waarschijnlijk nog niet wisten van jou?",
"Wat is het beste feestje dat je ooit hebt bijgewoond?",
"Wat is jouw slechtste gewoonte?",
"Waar zou jij wonen als je overal op de wereld zou kunnen wonen?",
"Wie kent jou het beste van iedereen?",
"Als je door de tijd terug kon reizen, welk advies zou je jezelf geven?",
"Wat is de leukste vakantie die je ooit hebt gehad?",
"Wat is je ergste vakantie ervaring ooit?",
"Als je een dag zou kunnen doen wat je zelf wilt, wat zou je dan doen?",
"Wat is het meest beschamende dat je ooit gedaan hebt toen je dronken was?",
"Wat is het leukste waar je ooit 50 euro aan hebt uitgegeven?",
"Op welke beroemdheid lijk je volgens sommige mensen?",
"Geloof jij in karma?",
"Wat was jouw favoriete programma toen je klein was?",
"Je gaat over één week dood, wat wil je nog doen?",
"Als je een dier zou zijn, welk dier was dat dan?",
"Wat zijn je dagdromen?",
"Hoe vaak ben je verliefd geweest?",
"Wat is jouw grootste blunder?",
"Waarom ben jij een goede vriend/vriendin?",
"Welke jongen/meisje heb je voor het laatst geappt?",
"Over wie roddel je wel eens?",
"Waarin lijk je op je moeder?",
"Welk liedje zing jij onder de douche?",
"Wat weten de meeste mensen niet over jou?",
"Hoe ziet je leven er over 5 jaar uit?",
"Van welke muziek word je blij?",
"Wat is je grootste angst?",
"Lijk je op je vrienden?",
"Vind je jezelf introvert en extravert?",
"Wat is voor jou geluk?",
"Waar schaamt je je voor?",
"Wanneer heb je voor het laatst gehuild?",
"Hoe moedig ben je?",
"Vind je dat je goed kunt zingen?",
"Waarin lijk je op je vader?",
"Ben je bijgelovig?",
"Wanneer schaam je je voor je ouders?",
"Van wie heb je wel eens een geheim doorverteld?",
"Wat is het meest brutale dat je hebt gedaan?",
"Heb je wel eens gelogen tegen een leraar?",
"Wat is het engste verhaal dat je ooit hebt gehoord?",
"Hoe versier je een jongen/meisje?",
"Heb je wel eens iets gestolen?",
"Waar word je verlegen van?",
"Wat doe je het liefst als je een dag alleen bent?",
"Met wie zou je graag willen zoenen?",
"Ben je bang in het donker?",
"In welke volgorde droog jij je af?",
"Ligt er iets in je kamer waar jij je voor schaamt?",
"Wat is het laatste dat je doet voordat je gaat slapen?",
"Heb je wel eens in het zwembad geplast?",
"Geloof je in geesten?",
"Wie is de grappigste persoon die je kent?",
"Door welk liedje moet je altijd huilen?",
"Wat zou je aan jezelf willen veranderen?",
"Op well lichaamsdeel ben je trots?",
"Als je iets aan jezelf kon veranderen wat zou dat zijn?",
"Wie is je grootste liefde?",
"Van wie heb je het meest geleerd?",
"Heb je een ander wel eens verdriet gemaakt?",
"Waaraan/aan wie ben je het meest gehecht?",
"Wat is de beste plek om te wonen?",
"Wie zou je, behalve jezelf, willen zijn?",
"Wat vind je het mooiste moment van de dag?",
"Wat maakt jou uniek?",
"Wat is jouw levensmotto?",
"Welke superheld zou je willen zijn en waarom?",
"Hoe ziet voor jou de perfecte dag eruit?",
"Zou je liever de slimste persoon in een groep mensen zijn of de knapste?",
"Zou je liever doorgaan met je huidige leven of opnieuw beginnen als dat mogelijk was?",
"Zou je liever doof zijn of blind?",
"Zou je liever behaard willen zijn of helemaal zonder haren?",
"Zou je liever altijd 10 minuten te laat zijn of 20 minuten te vroeg?",
"Zou je liever al je foto’s kwijtraken of al je geld?",
"Zou je liever knap en dom willen zijn of intelligent maar lelijk?",
"Zou je liever door iedereen gevreesd worden of geliefd zijn door iedereen?",
"Zou je liever de liefde van je leven ontmoeten of drie miljoen euro vinden?",
"Zou je liever nooit geen vlees meer eten of groenten?",
"Zou je liever geen kinderen krijgen of alleen drielingen?",
"Zou je liever rijst bij elke maaltijd eten of brood?",
"Zou je liever 5cm groter of 5cm kleiner willen zijn?",
"Zou je liever iets te laat zijn of veel te vroeg?",
"Zou je liever alleen werken of met een groep mensen?",
"Zou je liever teveel overgewicht of ondergewicht hebben?",
"Zou je liever meer tijd willen of meer geld?",
"Zou je liever jezelf blijven of iemand anders (als dat kon)?",
"Zou je liever te druk zijn of verveeld?",
"Zou je liever kaal zijn of altijd een slechte kapbeurt meemaken?",
"Zou je liever een maand zonder internet zitten of een maand niet douchen?",
"Zou je liever gratis Wifi hebben in de trein of gratis koffie?",
"Zou je liever als zwerver in de stad willen leven of ver van de mensen in de natuur?",
"Zou je liever stoppen met social media apps of televisie kijken?",
"Zou je liever sneller kunnen typen of sneller kunnen lezen?",
"Zou je liever een zelfrijdende auto willen of een volledig geautomatiseerd huis?",
"Zou je liever nooit je sleutels kwijtraken of je smartphone?",
"Zou je liever aan het strand wonen of in een huis in de bossen?",
"Zou je liever zonder je linkerhand verder moeten of je rechtervoet?",
"Zou je liever alleen maar scherp gekruid eten of alleen maar smaakloos eten?",
"Zou je liever zelf een huis ontwerpen en bouwen of het door een architect en aannemer laten doen?",
"Zou je liever de badkamer poetsen of de vaat wassen?",
"Zou je liever de beste speler van het veld zijn maar toch verliezen of winnen terwijl je op de bank zit?",
"Zou je liever voor een groep mensen die je kent zingen of voor een groep onbekende personen?",
"Zou je liever twee weken gaan backpacken in Azië of lig je liever in twee weken aan het strand in Spanje?",
"Zou je liever geld willen voor je verjaardag of een cadeau?",
"Zou je liever in een klein huis in een goede buurt wonen of een riant huis in een slechte buurt?",
"Zou je liever parachutespringen of bungee jumpen?",
"Zou je liever buiten werken of een kantoorbaan hebben?",
"Zou je liever het goede of het slechte nieuws eerst horen?",
"Zou je liever voor jezelf werken of voor een baas?",
"Zou je liever stelen of vreemdgaan?",
"Zou je liever meer uren per dag maar minder dagen per week willen werken of meer dagen per week en minder uren per dag?",
"Zou je liever een nacht in een luxueus hotel doorbrengen of in een tent met mooi uitzicht?",
"Zou je liever in een land wonen waar het altijd koud is of in een zomers land?",
"Zou je liever één beste vriend(in) hebben of vele goede kennissen?",
"Zou je liever de hele dag op een huilend kind passen of een week lang een zeurende schoonmoeder op bezoek hebben?",
"Zou je liever opgesloten zijn in een bibliotheek of in een avonturenpark?",
"Zou je liever ten huwelijk gevraagd worden met veel publiek erbij of tijdens een intiem onderonsje?",
"Zou je liever in een grot wonen of een boomhuis?",
"Zou je liever een kok in huis willen of een schoonmaakster?",
"Zou je liever geen bezoekers op je bruiloft willen of op je begrafenis?",
"Zou je liever nooit meer zweten of het koud hebben?",
"Zou je liever een koe zijn of een kip?",
"Zou je liever echte liefde vinden of 1 miljoen euro?",
"Zou je liever een jacht willen hebben of een vliegtuig?",
"Zou je liever meer geld willen of meer tijd?",
"Zou je liever Batman of Spiderman zijn?",
"Zou je liever 2 keer zo klein of 2 keer zo zwaar willen zijn?",
"Zou je liever jezelf blijven of iemand anders worden?",
"Zou je liever de slimste persoon willen zijn of de knapste?",
"Zou je liever kunnen vliegen of gedachten lezen?",
"Zou je liever doof zijn of blind?",
"Zou je liever een stand-up comedian zijn of een pianist?",
"Zou je liever altijd weten dat iemand liegt of zelfs nooit betrapt worden op liegen?",
"Zou je liever een advocaat of een dokter willen zijn?",
"Zou je liever je voorouders willen ontmoeten of je toekomstige volwassen kleinkinderen?",
"Zou je liever het begin van de aarde willen meemaken of het einde?",
"Zou je liever alle talen spreken of met dieren kunnen praten?",
"Zou je liever altijd willen weten als iemand liegt of zelf kunnen liegen en niemand het door heeft?",
"Zou je liever voor een dag kunnen vliegen of onzichtbaar zijn?",
"Zou je liever een jaar lang dezelfde dag herleven of een jaar verliezen?",
"Zou je liever een succesvolle acteur willen zijn of regisseur?",
"Zou je liever alleen op een onbewoond eiland zitten of samen met iemand die niet kan ophouden met praten?",
"Zou je liever het nieuws presenteren of meedoen aan een realityshow?",
"Zou je liever een Nobel prijs winnen of een Olympische medaille?",
"Zou je liever vier kinderen willen en geen geld of geen kinderen en vier miljoen euro?",
"Zou je liever willen weten wanneer je dood gaat of hoe je dood gaat?",
"Zou je liever nooit meer in de file staan of nooit meer struikelen in het openbaar",]

players = {'Marvin': {'nr': phone_number_1, 'ctr': 'mentee'}, 'Ferdaws': {'nr': phone_number_2, 'ctr': 'mentor'}}

@app.route('/')
def shoot_me():
	question = random.choice(questions)
	player = random.choice(list(players.keys()))
	number = players[player]['nr']
	counterpart = players[player]['ctr']
	body = f'Yo {player}, hier een vraag aan je {counterpart}:\n{question}'
	message = {'body': body,
	'from_': '+17402008194',
	'to': number}
	message = client.messages.create(**message)
	return 'OK'

if __name__ == "__main__":
	main()